# Generated by Django 4.2 on 2023-04-09 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fanza', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Video',
            new_name='Porn',
        ),
    ]
